source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxEasing_Example', :exclusive => true do
  pod "RxEasing", :path => "../"
  pod 'RxCocoa', '~> 2.0.0-beta.4'
  pod 'JBChartView', '~> 2.8'
end
