source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'RxEasing_Example' do
  pod "RxEasing", :path => "../"
  pod 'RxCocoa', '~> 4.4'
  pod 'RxOptional', '~> 3.6'
  pod 'JBChartView', '~> 2.8'
end
